export const INVOKE_CHANNELS = [
  'accounts:create', 'accounts:delete', 'accounts:list', 'accounts:refreshExchangeRates', 'accounts:update',
  'ai:ask', 'ai:clearApiKey', 'ai:clearHistory', 'ai:createDraft', 'ai:createTransactionBatchDrafts',
  'ai:explainDecision', 'ai:getSettings', 'ai:getSummaryPreview', 'ai:history', 'ai:listModels', 'ai:periodSummary',
  'ai:renegotiationDraft', 'ai:saveSettings', 'ai:setApiKey', 'ai:summary',
  'anomalies:dismiss', 'anomalies:list',
  'app:checkUpdate', 'app:version',
  'assets:create', 'assets:createReminder', 'assets:delete', 'assets:deleteReminder', 'assets:getNetWorthHistory',
  'assets:getSummary', 'assets:list', 'assets:listReminders', 'assets:update',
  'backgroundService:disable', 'backgroundService:enable', 'backgroundService:status',
  'backup:chooseFolder', 'backup:export', 'backup:exportIncremental', 'backup:import', 'backup:importIncremental',
  'bills:create', 'bills:delete', 'bills:duplicate', 'bills:getPriceIncreases', 'bills:getUpcoming', 'bills:list',
  'bills:markAsPaid', 'bills:update',
  'budgets:create', 'budgets:delete', 'budgets:getRangeTotals', 'budgets:list', 'budgets:update',
  'categories:create', 'categories:delete', 'categories:list', 'categories:suggestFromHistory', 'categories:update',
  'db:path',
  'debts:compareVsInvest', 'debts:create', 'debts:createBill', 'debts:delete', 'debts:getSummary', 'debts:list',
  'debts:simulate', 'debts:update',
  'debts:listAgreements', 'debts:createAgreement', 'debts:cancelAgreement',
  'dialog:openDocument',
  'documents:delete', 'documents:import', 'documents:list', 'documents:open',
  'export:csv', 'export:pdf',
  'family:getSettlement',
  'familyMembers:create', 'familyMembers:delete', 'familyMembers:list', 'familyMembers:update',
  'forecast:endOfMonth', 'forecast:get',
  'goals:addContribution', 'goals:create', 'goals:delete', 'goals:deleteContribution', 'goals:list',
  'goals:listContributions', 'goals:update',
  'import:confirm', 'import:preview',
  'investments:create', 'investments:createOperation', 'investments:delete', 'investments:deleteOperation',
  'investments:getSummary', 'investments:list', 'investments:listOperations', 'investments:update',
  'invoices:close', 'invoices:create', 'invoices:delete', 'invoices:getBestPurchaseWindow', 'invoices:getCardStates', 'invoices:listForAccount',
  'invoices:listUpcoming', 'invoices:markPaid', 'invoices:update',
  'irpf:confirmImport', 'irpf:downloadTemplate', 'irpf:exportCSV', 'irpf:exportPDF', 'irpf:getCapitalGains',
  'irpf:getReport', 'irpf:previewImport',
  'market:getQuotes', 'market:refresh',
  'mei:createDAS', 'mei:deleteDAS', 'mei:getReport', 'mei:markDASPaid',
  'mobileSync:cancelPairing', 'mobileSync:confirmPairing', 'mobileSync:listDevices', 'mobileSync:revokeDevice',
  'mobileSync:startListener', 'mobileSync:stopListener',
  'ocr:scanBoleto', 'ocr:scanReceipt',
  'openFinance:belvoCheckConnection', 'openFinance:belvoStartConnection', 'openFinance:clearProviderSecrets',
  'openFinance:disableProvider', 'openFinance:getBalanceAlertSettings', 'openFinance:getBalanceDropAlerts',
  'openFinance:getCashFlowForecast', 'openFinance:getConsolidatedBalance', 'openFinance:getOverview',
  'openFinance:getSettings', 'openFinance:klaviCreateConsent', 'openFinance:klaviImportReport',
  'openFinance:klaviRequestReport', 'openFinance:klaviStartConnection', 'openFinance:saveBalanceAlertSettings',
  'openFinance:saveProvider', 'openFinance:syncProvider', 'openFinance:testProvider',
  'pix:deleteRecipient', 'pix:getPayment', 'pix:listPayments', 'pix:listRecipients', 'pix:saveRecipient',
  'pix:simulatePayment', 'pix:validateKey',
  'radar:dismiss', 'radar:list',
  'receivables:create', 'receivables:delete', 'receivables:duplicate', 'receivables:getPriceIncreases',
  'receivables:getUpcoming', 'receivables:list', 'receivables:markAsReceived', 'receivables:update',
  'recurrenceDetection:dismiss', 'recurrenceDetection:list',
  'security:changePassword', 'security:disable', 'security:enable', 'security:status', 'security:unlock',
  'settings:clearSmtpPassword', 'settings:getAll', 'settings:moneyDiagnostic', 'settings:set', 'settings:setMany',
  'sync:pull', 'sync:push', 'sync:status',
  'transactions:create', 'transactions:createInstallments', 'transactions:delete', 'transactions:get',
  'transactions:getExpenseAnalytics', 'transactions:getExpenseSubcategoryBreakdown',
  'transactions:getExpensesByCategory', 'transactions:getExpensesByCategoryRange',
  'transactions:getFilteredMonthlyHistory', 'transactions:getIncomeAnalytics',
  'transactions:getInstallmentCommitments', 'transactions:getMonthlyHistory', 'transactions:getSummaryRange',
  'transactions:list', 'transactions:update',
  'updater:check', 'updater:download', 'updater:install', 'updater:supported',
  'weeklyReview:getState', 'weeklyReview:getStreak', 'weeklyReview:setState',
  'window:close', 'window:focus', 'window:minimize', 'window:toggleMaximize',
] as const;

export const SEND_CHANNELS = ['security:unlocked', 'shell:openExternal'] as const;
export const EVENT_CHANNELS = ['mobileSync:event', 'updater:status'] as const;

export type InvokeChannel = typeof INVOKE_CHANNELS[number];
export type SendChannel = typeof SEND_CHANNELS[number];
export type EventChannel = typeof EVENT_CHANNELS[number];

export function isAllowedChannel(channel: unknown, allowed: readonly string[]): channel is string {
  return typeof channel === 'string' && allowed.includes(channel);
}
